### ISSUE TITLE
CQL Parameters page busted

### ISSUE THREAD

**Issue by drwelby** [Maxar-Corp/maxar-geospatial-platform#6]
on https://maxar-geospatial-platform.readthedocs.io/en/latest/MaxarPortalConnect/streaming/#cql-filters there's a link to `CQL Parameters` that resolves to `ogc/get_filter_parameters` which renders in a very broken state.

**Comment by maxar-gcs** [comment]
This page is from the QGIS plugin that is no longer part of this documented package. References to that page have been removed.
