### ISSUE TITLE
Response errors get eaten

### ISSUE THREAD

**Issue by drwelby** [Maxar-Corp/maxar-geospatial-platform#7]
https://github.com/Maxar-Corp/maxar-geospatial-platform/blob/main/src/MGP_SDK/process.py#L26

This function duplicates the functionality of `response.raise_for_status()` but also hijacks the error text. When an order doesn't validate it sends back a 400 with a human readable message but by raising a new exception without the original response text the user can't tell what the problem with their settings is.

**Comment by maxar-gcs** [comment]
This has been corrected as of v1.2.1.

**Comment by drwelby** [comment]
This does not address the issue that the most generic `Exception` class is raised which renders Pythonic try/except patterns either useless or reliant on fragile error message parsing.

If you use Request's `response.raise_for_status()`, you'll get specific Exception subclasses you can write logic against.

https://requests.readthedocs.io/en/latest/_modules/requests/exceptions/

**Comment by maxar-gcs** [comment]
Response handler has been update to return `response.raise_for_status` when an API error is returned.
